language: objective-c
osx_image: xcode6.4

branches:
  only:
    master

env: export LANG=en_US.UTF-8

install:
  - bundle install
  - brew install carthage 2> /dev/null
  - carthage bootstrap -v
script: bin/test
